project:               
    type: website 
    output-dir: docs            
website:
    title: "First Principles"
    description: "Deep dives into ML and distributed training."
    navbar:                                                    
      left:                             
        - href: index.qmd
          text: "Home"                       
        - href: about.qmd
          text: "About"    
format:         
    html:
      theme: cosmo
      css: styles.css
      toc: true      
      toc-depth: 3     